Update thirdparty.yml
italia/developers-italia-backend pull request #284
Opened 2022-06-15 20:23 UTC by MicheleTiledesk

Adding Tiledesk repositories

2022-06-15 20:32 UTC, bfabio requested changes

2022-06-15 20:58 UTC, MicheleTiledesk commented on crawler/whitelist/thirdparty.yml
> +    - "https://github.com/Tiledesk/chat21-web-widget"
I added publiccode.yml to the other repos too. 
Could you please add all of them?
Thx!

2022-06-16 06:43 UTC, bfabio commented on crawler/whitelist/thirdparty.yml
> +    - "https://github.com/Tiledesk/chat21-web-widget"
Thanks @MicheleTiledesk, there's no need to add publiccode.yml in the other components: we can have just the first one, representing the whole solution. We often internally call it "metarepo"

2022-06-16 07:09 UTC, bfabio commented on crawler/whitelist/thirdparty.yml
> +
```suggestion

```

2022-06-16 07:09 UTC, bfabio commented on crawler/whitelist/thirdparty.yml
>      - "https://github.com/dej611/spid-react-button"
```suggestion
    - "https://github.com/dej611/spid-react-button"

```

2022-06-16 07:09 UTC, bfabio approved these changes

2022-06-16 07:15 UTC, MicheleTiledesk commented
Ciao Fabio,

grazie mille per il supporto.

Ho chiuso la pull request. Fammi sapere se c'è altro che devo fare per la
pubblicazione sul vostro catalogo.

Buona giornata!
Michele

Il giorno gio 16 giu 2022 alle ore 09:09 Fabio Bonelli <
***@***.***> ha scritto:

> ***@***.**** approved this pull request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/italia/developers-italia-backend/pull/284#pullrequestreview-1008593272>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZHAQUMIQUY2BMOY263JXADVPLHMJANCNFSM5Y4RJZ5A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-06-16 07:34 UTC, merged

2022-06-16 07:37 UTC, bfabio commented
Ciao @MicheleTiledesk, ho fatto merge della modifica (chiudere la PR equivale a non accettarla :wink:).

Il job gira di notte e il sito è aggiornato ogni mattina, quindi domani dovresti vedere Titledesk su developers.italia.it.

2022-06-16 07:44 UTC, MicheleTiledesk commented
Ciao Fabio,

grazie e scusa per qualche grattacapo che vi ho dato. :-)

Fai che sono l'unico non sviluppatore del Team. Mi è però servito per
prendere dimestichezza con GitHub.

La prossima volta andrà sicuramente meglio.

A presto!
Michele

Il giorno gio 16 giu 2022 alle ore 09:37 Fabio Bonelli <
***@***.***> ha scritto:

> Ciao @MicheleTiledesk <https://github.com/MicheleTiledesk>, ho fatto
> merge della modifica (chiudere la PR equivale a non accettarla 😉).
>
> Il job gira di notte e il sito è aggiornato ogni mattina, quindi domani
> dovresti vedere Titledesk su developers.italia.it.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/italia/developers-italia-backend/pull/284#issuecomment-1157336342>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZHAQULZ47PS4H2XZYGTGLDVPLKTLANCNFSM5Y4RJZ5A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>